Resources:  
    HrkMediaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hrk-media-${sls:stage}-${aws:accountId} # Använd ${sls:stage} direkt här
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - ${self:custom.frontendUrls.${self:custom.stage}}
              MaxAge: 3000

    HrkAppFrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hrk-app-frontend-${sls:stage}-${aws:accountId} # Garanterat unikt namn
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        WebsiteConfiguration: # Konfigurerar den som en webbserver
          IndexDocument: index.html
          ErrorDocument: index.html # Viktigt för Single Page Applications som React