service: hrk-auth-service
configValidationMode: error

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: eu-north-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-iam-roles-per-function   

package:
  individually: true

functions:
  - ${file(./yaml/auth-functions.yml)}