Resources:
  HrkDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HrkMainTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  HrkInviteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HrkInviteTable-${opt:stage}
      AttributeDefinitions:
        - AttributeName: "inviteId" 
          AttributeType: "S"
      KeySchema:
        - AttributeName: "inviteId"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: "timeToLive"
        Enabled: true

  HrkAttendanceSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HrkAttendanceSessionsTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: date           
          AttributeType: S
        - AttributeName: sessionId      
          AttributeType: S
        - AttributeName: attendanceCode 
          AttributeType: S
        - AttributeName: groupSlug
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH   
        - AttributeName: sessionId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: AttendanceCodeIndex
          KeySchema:
            - AttributeName: attendanceCode
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GroupDateIndex
          KeySchema:
            - AttributeName: groupSlug  
              KeyType: HASH
            - AttributeName: date   
              KeyType: RANGE
          Projection:
            ProjectionType: ALL 
      TimeToLiveSpecification:
        AttributeName: "expiresAt"
        Enabled: true
