Resources: 
  HrkDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HrkMainTable-${opt:stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  HrkInviteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HrkInviteTable-${opt:stage}
      AttributeDefinitions:
        - AttributeName: "inviteId" 
          AttributeType: "S"
      KeySchema:
        - AttributeName: "inviteId"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: "timeToLive"
        Enabled: true
