service: infra-service
frameworkVersion: '4'

provider:
  name: aws
  region: eu-north-1
  stage: ${opt:stage, 'dev'}

custom:
  stage: ${sls:stage}
  frontendUrls:
    dev: 'http://localhost:5173'
    prod: 'https://app.hardrockskoren.se'

resources:
  - ${file(./database/dynamoDb.yml)}
  - ${file(./iam/cognito.yml)}
  - ${file(./storage/s3.yml)}

